src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=EventRepository::class)
 */
class Event
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez renseigner ce champs")
     */
    private $nom;

    /**
     * @ORM\Column(type="date", nullable=true)
     * @Assert\NotBlank(message="Veuillez renseigner ce champs")


     */

    private $date_debut;

    /**
     * @ORM\Column(type="date", nullable=true)


     *  @Assert\NotBlank(message="Veuillez renseigner ce champs")
     */
    private $date_fin;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotBlank(message="Veuillez renseigner ce champs")
     */
    private $lieu;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)

     * @Assert\Length(
     *      min = 10,
     *      max = 250,
     *      minMessage = "la description doit comporter au moins {{ limit }} caractères",
     *      maxMessage = "la description ne peut pas dépasser {{ limit }} caractères"
     * )
     * @Assert\NotBlank(message="Veuillez renseigner ce champs")
     */

    private $description;

    /**
     * @ORM\Column(type="float", nullable=true)
     * @Assert\Positive(message ="cette val")
     * @Assert\NotBlank(message="Veuillez renseigner ce champs")
     */

    private $prix;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)


     */
   
    private $image;

    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class, inversedBy="event")
     * @ORM\JoinColumn(nullable=false)
     */
    private $categorie;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(?\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(?\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getLieu(): ?string
    {
        return $this->lieu;
    }

    public function setLieu(?string $lieu): self
    {
        $this->lieu = $lieu;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(?float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }
}

src/Form/EventType.php
<?php

namespace App\Form;

use App\Entity\Event;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;

class EventType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('date_debut')
            ->add('date_fin')
            ->add('lieu')
            ->add('description')
            ->add('prix')
            ->add('image', FileType::class, [
                'mapped' => false,
                 'required' => false,

            ])
            ->add('categorie')
            ->add('Enregistrer',SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Event::class,
        ]);
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\Categorie;
use App\Entity\Event;
use App\Entity\Produit;
use App\Form\EventType;
use App\Form\ProduitType;
use App\Repository\EventRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\Routing\Annotation\Route;
use Gedmo\Sluggable\Util\Urlizer;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * @Route("/event")
 */
class EventController extends AbstractController
{
    /**
     * @Route("/admin", name="event_index", methods={"GET"})
     */
    public function index(Request $request,PaginatorInterface $paginator): Response
    { $donnees = $this->getDoctrine()->getRepository(Event::class)->findAll();
        $events = $paginator->paginate(
            $donnees,
            $request->query->getInt('page',1),
            4
        );
        return $this->render('event/index.html.twig', [
            'events' => $events,
        ]);
    }
    /**
     * @Route("/home", name="event_home", methods={"GET"})
     */
    public function index2(Request $request,PaginatorInterface $paginator): Response
    { $donnees = $this->getDoctrine()->getRepository(Event::class)->findAll();
        $events = $paginator->paginate(
            $donnees,
            $request->query->getInt('page',1),
            4
        );
        return $this->render('event/index_front.html.twig', [
            'events' => $events,
        ]);
    }
    /**
     * @Route("/partenaire", name="profile", methods={"GET"})
     */
    public function index3(Request $request,PaginatorInterface $paginator): Response
    { $donnees = $this->getDoctrine()->getRepository(Event::class)->findAll();
        $events = $paginator->paginate(
            $donnees,
            $request->query->getInt('page',1),
            4
        );
        return $this->render('Profile.html.twig', [
            'events' => $events,
        ]);
    }

    /**
     * @Route("/new", name="event_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $event = new Event();
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $uploadedFile = $form['image']->getData();
            if ($uploadedFile) {
                $destination = $this->getParameter('kernel.project_dir') . '/public/upload';
                $originalFilename = pathinfo($uploadedFile->getClientOriginalName(), PATHINFO_FILENAME);
                $newFilename = $originalFilename. '-' . uniqid() . '.' . $uploadedFile->guessExtension();
                $uploadedFile->move(
                    $destination,
                    $newFilename);
                $event->setImage($newFilename);

            }
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($event);
            $entityManager->flush();

            return $this->redirectToRoute('event_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('event/new.html.twig', [
            'event' => $event,
            'form' => $form->createView(),
        ]);
    }
    /**
     * @Route("/new/part", name="add_part", methods={"GET","POST"})
     */
    public function new1(Request $request): Response
    {
        $event = new Event();
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $uploadedFile = $form['image']->getData();
            if ($uploadedFile) {
                $destination = $this->getParameter('kernel.project_dir') . '/public/upload';
                $originalFilename = pathinfo($uploadedFile->getClientOriginalName(), PATHINFO_FILENAME);
                $newFilename = $originalFilename. '-' . uniqid() . '.' . $uploadedFile->guessExtension();
                $uploadedFile->move(
                    $destination,
                    $newFilename);
                $event->setImage($newFilename);

            }
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($event);
            $entityManager->flush();

            return $this->redirectToRoute('profile', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('event/add_front.html.twig', [
            'event' => $event,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/edit/", name="event_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Event $event): Response
    {
        $form = $this->createForm(EventType::class, $event);// creation formulaire
        $form->handleRequest($request);
        $oldFileName = $event->getImage();
        if ($form->isSubmitted() && $form->isValid()) {
            /** @var UploadedFile $uploadedFile */
            $uploadedFile = $form['image']->getData();

            if ($uploadedFile) {
                $destination = $this->getParameter('kernel.project_dir') . '/public/upload';
                $originalFilename = pathinfo($uploadedFile->getClientOriginalName(), PATHINFO_FILENAME);
                $newFilename =$originalFilename. '-' . uniqid() . '.' . $uploadedFile->guessExtension();
                $uploadedFile->move(
                    $destination,
                    $newFilename
                );
                $event->setImage($newFilename);
            }
            else{
                $event->setImage($oldFileName);
            }
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($event);
            $entityManager->flush();
            return $this->redirectToRoute('event_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('event/edit.html.twig', [
            'events' => $event,
            'form' => $form->createView(),
        ]);
    }
    /**
     * @Route("/{id}/edit/part", name="part_edit", methods={"GET","POST"})
     */
    public function  part(Request $request, Event $event): Response
    {
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {


            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('profile', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('event/edit_front.html.twig', [
            'event' => $event,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="event_show", methods={"GET"})
     */
    public function show(Event $event): Response
    {
        return $this->render('event/show.html.twig', [
            'event' => $event,
        ]);
    }
    /**
     * @Route("part/{id}", name="event_show_part", methods={"GET"})
     */
    public function partshow(Event $event): Response
    {
        return $this->render('event/show_front.html.twig', [
            'event' => $event,
        ]);
    }

    /**
     * @Route("/delete/{id}", name="event_delete")
     */
    public function deleteeventadmin(Request $request,$id)
    {

        $result=$this->getDoctrine()->getRepository(Event::class)->find($id);

        $entityManager=$this->getDoctrine()->getManager();
        $entityManager->remove($result);
        $entityManager->flush();
        $response = new Response();
        $response->send();
        return $this->redirectToRoute('event_index');


    }
    /**
     * @Route("/delete/part/{id}", name="event_del_part")
     */
    public function deleteeventpart(Request $request,$id)
    {

        $result=$this->getDoctrine()->getRepository(Event::class)->find($id);

        $entityManager=$this->getDoctrine()->getManager();
        $entityManager->remove($result);
        $entityManager->flush();
        $response = new Response();
        $response->send();
        return $this->redirectToRoute('profile');


    }
}

templates/event/_delete_form.html.twig
<form method="post" action="{{ path('event_delete', {'id': event.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ event.id) }}">
    <button class="btn">Delete</button>
</form>

templates/event/_form.html.twig
{{ form_start(form) }}

    {{ form_widget(form) }}
{{ form_row(form.image) }}


{{ form_end(form) }}

templates/event/add_front.html.twig
{% extends 'base_front.html.twig' %}
{% block title %}ajouter event{% endblock %}
{% block body %}

    <div class="main-panel">
        <div class="content-wrapper">

                <div class="card">
                    <div class="card-body">

                        <h4 style="color:#FFA500"  class="card-title">Ajouter évènements</h4>

                        {{ form_start(form,{'attr': {'novalidate': 'novalidate'}} ) }}
                        {{form_widget(form)}}
                        {{form_end(form)}}
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>
</section>
{% endblock %}

templates/event/edit.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}Modifier évènement{% endblock %}
{% block body %}
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">

                        <h4 style="color:#FFA500"  class="card-title">Modifier évènement</h4>

                        {{form_start(form ,{'attr':{'class':'form-horizontal'}})}}
                        {{form_widget(form)}}
                        {{form_end(form)}}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/event/edit_front.html.twig
{% extends 'base_front.html.twig' %}

{% block title %}Modifier évènement{% endblock %}
{% block body %}
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">

                        <h4 style="color:#FFA500"  class="card-title">Modifier évènement</h4>

                        {{form_start(form ,{'attr':{'class':'form-horizontal'}})}}
                        {{form_widget(form)}}
                        {{form_end(form)}}


                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/event/index.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}Event{% endblock %}
{% block body %}
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 style="color:#FFA500"  class="card-title"> Liste des évènements</h4>

                        <ul class="navbar-nav w-100">
                            <li class="nav-item w-100">
                                <form class="nav-link mt-2 mt-md-0 d-none d-lg-flex search">
                                    <input type="text" id="myInput" alt="" onkeyup="myFunction()" class="form-control" placeholder="Chercher partenaire">
                                </form>
                            </li>
                        </ul>
                        <div id="myTable" class="table-responsive">
                            <table class="table" class="table table-striped">
                                <thead>
                                <tr>

                                    <th>Nom</th>
                                    <th>Date_debut</th>
                                    <th>Date_fin</th>
                                    <th>Lieu</th>

                                    <th>Prix</th>

                                    <th>actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for event in events %}
                                    <tr>
                                        <td>{{ event.nom }}</td>
                                        <td>{{ event.dateDebut ? event.dateDebut|date('Y-m-d') : '' }}</td>
                                        <td>{{ event.dateFin ? event.dateFin|date('Y-m-d') : '' }}</td>
                                        <td>{{ event.lieu }}</td>
                                        <td>{{ event.prix }}</td>
                                        <td><label class="badge badge-danger"> <a href="{{ path('event_delete', {'id': event.id}) }}"><i class="mdi mdi-delete"></i></a></label><label class="badge badge-info"><a href="{{ path('event_edit', {'id': event.id}) }}"><i class="mdi mdi-table-edit"></i></a></label><label class="badge badge-warning"><a href="{{ path('event_show', {'id': event.id}) }}"><i class="mdi mdi-information-outline"></i></a></label></td>

                                    </tr>

                                {% else %}
                                    <tr>
                                        <td colspan="3">tableau vide</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                            {{ knp_pagination_render(events) }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/event/new.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}ajouter Event{% endblock %}

{% block body %}
<div class="main-panel">
    <div class="content-wrapper">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">

                    <h4 style="color:#FFA500"  class="card-title">Ajouter évènements</h4>

                    {{ form_start(form,{'attr': {'novalidate': 'novalidate'}} ) }}
                    {{form_widget(form)}}
                    {{form_end(form)}}
                </div>
            </div>
        </div>
    </div>
</div>

    <a href="{{ path('event_index') }}">back to list</a>
{% endblock %}

templates/event/show.html.twig
{% extends 'base-back.html.twig' %}



{% block title %}event{% endblock %}

{% block body %}
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 style="color:#FFA500"  class="card-title">Evènement</h4>

                        <table class="table">
                            <img style=" display: block;
                      margin-left: auto;
                      margin-right: auto;
                      width: 50%;"  src="{{ asset( 'upload/'~event.image)}}"  />
                            <tbody>
                            <tr>
                                <th>Id</th>
                                <td>{{ event.id }}</td>
                            </tr>
                            <tr>
                                <th>Date_debut</th>
                                <td>{{ event.dateDebut ? event.dateDebut|date('Y-m-d') : '' }}</td>
                            </tr>
                            <tr>
                                <th>Date_fin</th>
                                <td>{{ event.dateFin ? event.dateFin|date('Y-m-d') : '' }}</td>
                            </tr>
                            <tr>
                                <th>Lieu</th>
                                <td>{{ event.lieu }}</td>
                            </tr>
                            <tr>
                                <th>Description</th>
                                <td>{{ event.description }}</td>
                            </tr>





                            </tbody>
                        </table>
                        <a href="{{ path('event_index') }}" type="button" class="btn btn-warning btn-fw">Liste évènements</a>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/event/show_front.html.twig
{% extends 'base_front.html.twig' %}
{% block title %}event{% endblock %}
{% block body %}

<!-- Hero Section-->
<section class="pt-7 pb-5 d-flex align-items-end dark-overlay bg-cover" style="background-image: url('{{ asset( 'upload/'~event.image) }}');">
    <div class="container overlay-content">
        <div class="d-flex justify-content-between align-items-start flex-column flex-lg-row align-items-lg-end">
            <div class="text-white mb-4 mb-lg-0">
                <div class="badge badge-pill badge-transparent px-3 py-2 mb-4">{{ event.categorie }}</div>
                <h1 class="text-shadow verified">{{ event.nom }}</h1>
                <p><i class="fa-map-marker-alt fas mr-2"></i> {{ event.lieu }}</p>
                <p class="mb-0 d-flex align-items-center"><i class="fa fa-xs fa-star text-primary"></i><i class="fa fa-xs fa-star text-primary"></i><i class="fa fa-xs fa-star text-primary"></i><i class="fa fa-xs fa-star text-primary"></i><i class="fa fa-xs fa-star text-gray-200 mr-4">                   </i>8 Reviews</p>
            </div>
            <div class="calltoactions"><a class="btn btn-primary" href="#leaveReview" onclick="$('#leaveReview').collapse('show')" data-smooth-scroll>Leave a Review</a></div>
        </div>
    </div>
</section>
<section class="py-6">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <!-- About Listing-->
                <div class="text-block">
                    <h3 class="mb-3">Description</h3>
                    <p class="text-muted">{{ event.description }}</p>
                 </div>
                <div class="text-block">
                    <!-- Listing Location-->
                    <h3 class="mb-4">Location</h3>
                    <div class="map-wrapper-300 mb-3">
                        <div class="h-100" id="detailMap"></div>
                    </div>
                </div>



            </div>
            <div class="col-lg-4">
                <div class="pl-xl-4">
                    <!-- Opening Hours      -->
                    <div class="card border-0 shadow mb-5">
                        <div class="card-header bg-gray-100 py-4 border-0">
                            <div class="media align-items-center">
                                <div class="media-body">
                                    <p class="subtitle text-sm text-primary">Opening in 5 minutes</p>
                                    <h4 class="mb-0">Opening Hours </h4>
                                </div>
                                <svg class="svg-icon svg-icon svg-icon-light w-3rem h-3rem ml-3 text-muted">
                                    <use xlink:href="#wall-clock-1"> </use>
                                </svg>
                            </div>
                        </div>
                        <div class="card-body">
                            <table class="table text-sm mb-0">
                                <tr>
                                    <th class="pl-0 border-0">DATE</th>
                                    <td class="pr-0 text-right border-0">{{ event.dateDebut ? event.dateDebut|date('Y-m-d') : '' }}</td>
                                </tr>
                                <tr>
                                    <th class="pl-0">Monday</th>
                                    <td class="pr-0 text-right">{{ event.dateFin ? event.dateFin|date('Y-m-d') : '' }}</td>
                                </tr>
                            </table>
                        </div>
                    </div>
                    <!-- Contact-->
                    <div class="card border-0 shadow mb-5">
                        <div class="card-header bg-gray-100 py-4 border-0">
                            <div class="media align-items-center">
                                <div class="media-body">
                                    <p class="subtitle text-sm text-primary">Drop Us a Line</p>
                                    <h4 class="mb-0">Contact</h4>
                                </div>
                                <svg class="svg-icon svg-icon svg-icon-light w-3rem h-3rem ml-3 text-muted">
                                    <use xlink:href="#fountain-pen-1"> </use>
                                </svg>
                            </div>
                        </div>
                        <div class="card-body">
                            <ul class="list-unstyled mb-4">
                                <li class="mb-2"> <a class="text-gray-00 text-sm text-decoration-none" href="#"><i class="fa fa-phone mr-3"></i><span class="text-muted">(020) 123 456 789</span></a></li>
                                <li class="mb-2"> <a class=" text-sm text-decoration-none" href="#"><i class="fa fa-envelope mr-3"></i><span class="text-muted">info@example.com</span></a></li>
                                <li class="mb-2"> <a class=" text-sm text-decoration-none" href="#"><i class="fa fa-globe mr-3"></i><span class="text-muted">www.example.com</span></a></li>
                                <li class="mb-2"> <a class="text-blue text-sm text-decoration-none" href="#"><i class="fab fa-facebook mr-3"></i><span class="text-muted">Facebook</span></a></li>
                                <li class="mb-2"> <a class=" text-sm text-decoration-none" href="#"><i class="fab fa-twitter mr-3"></i><span class="text-muted">Twitter</span></a></li>
                                <li class="mb-2"> <a class=" text-sm text-decoration-none" href="#"><i class="fab fa-instagram mr-3"></i><span class="text-muted">Instagram</span></a></li>
                                <li class="mb-2"> <a class=" text-sm text-decoration-none" href="#"><i class="fab fa-google-plus mr-3"></i><span class="text-muted">Google+</span></a></li>
                            </ul>
                            <div class="text-center"><a class="btn btn-outline-primary btn-block" href="#"> <i class="far fa-paper-plane mr-2"></i>Send a Message</a></div>
                        </div>
                    </div>
                    <div class="text-center">
                        <p><a class="text-secondary" href="#"> <i class="fa fa-heart"></i> Bookmark This Listing</a></p><span>79 people bookmarked this place </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}